PROXY_SOCKET_READ_TIMEOUT: float = 5
PROXY_SOCKET_READ_BYTE_SIZE: int = 10
PROXY_SOCKET_IDDLE_TIMEOUT: int = 60

PROXY_SOCKET_KEEPALIVE: int = 1
PROXY_SOCKET_KEEPIDLE: int = 0
PROXY_SOCKET_KEEPINTVL: int = 3
PROXY_KEEPCNT: int = 5
